# Generated by Django 5.1.5 on 2025-02-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_quote_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
