# Generated by Django 5.1.5 on 2025-02-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_photos_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='catagory',
            field=models.CharField(choices=[('nature', 'Nature'), ('travel', 'Travel'), ('animals', 'Animals')], default='nature', max_length=20),
        ),
    ]
