# Generated by Django 5.1.5 on 2025-02-11 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_photos_catagory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photos',
            new_name='Post',
        ),
    ]
