# Generated by Django 5.1.5 on 2025-02-11 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_photos_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='header',
        ),
    ]
